//! Acceptance test: the SP1 validator factory ([`build_validator`]) must emit a
//! full Aiken project that `aiken check`s green against the pinned fixtures —
//! driven exactly as a host would drive it (canonicalize the committed raw SP1
//! artifacts, feed the committed outer proof), with the standard test suite
//! generated by the factory rather than hand-written here.
//!
//! The project is written under the workspace `target/` (gitignored) so it can
//! be inspected after the run. If `aiken` is not on `PATH` the test still
//! validates generation and the `aiken check` step is skipped with a notice.

use std::path::{Path, PathBuf};
use std::process::Command;

use zkwrap_core::OuterProof;
use zkwrap_sp1::{build_validator, canonicalize, Sp1ValidatorRequest};

fn repo_path(rel: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join(rel)
}

fn read(rel: &str) -> String {
    std::fs::read_to_string(repo_path(rel)).unwrap()
}

fn read_bytes(rel: &str) -> Vec<u8> {
    std::fs::read(repo_path(rel)).unwrap()
}

#[test]
fn factory_emits_aiken_check_passing_project() {
    // Drive it like a host: canonicalize the committed raw SP1 artifacts, then
    // pair the bundle with the committed outer proof.
    let proof_bytes = read_bytes("fixtures/sp1-hello-world/proof_bytes.bin");
    let public_values = read_bytes("fixtures/sp1-hello-world/public_values.bin");
    let proof_nonce = read_bytes("fixtures/sp1-hello-world/proof_nonce.bin");
    let vkey_hash: [u8; 32] = read_bytes("fixtures/sp1-hello-world/vkey_hash.bin")
        .as_slice()
        .try_into()
        .unwrap();
    let canonical = canonicalize(&proof_bytes, &public_values, vkey_hash).unwrap();

    let vk_json = read("fixtures/groth16-setup/outer_vk.json");
    let outer = OuterProof::from_json(&read("fixtures/sp1-outer-proof.json")).unwrap();

    let project = build_validator(&Sp1ValidatorRequest {
        canonical: &canonical,
        outer_proof: &outer,
        outer_vk_json: &vk_json,
        public_values: &public_values,
        proof_nonce: &proof_nonce,
        project_name: "zkwrap/sp1_groth16",
    })
    .unwrap();

    // Generation sanity: required files present, no unrendered template holes.
    let validator = project
        .get("validators/verify.ak")
        .expect("validators/verify.ak");
    let layer1 = project
        .get("lib/zkwrap/groth16.ak")
        .expect("lib/zkwrap/groth16.ak");
    let layer2 = project.get("lib/zkwrap/sp1.ak").expect("lib/zkwrap/sp1.ak");
    for (name, src) in [("groth16", layer1), ("sp1", layer2), ("verify", validator)] {
        assert!(
            !src.contains("{{") && !src.contains("{%"),
            "{name}.ak has unrendered holes"
        );
    }
    assert!(validator.contains("const vkey_hash: Int = 0x00748c3f"));
    assert!(validator.contains("const vk_root: Int = 0x"));

    // Materialize under the (gitignored) target dir for inspection + aiken check.
    let out_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../target/generated/sp1-verifier");
    let _ = std::fs::remove_dir_all(&out_dir);
    project.write_to(&out_dir).unwrap();
    eprintln!("generated project at {}", out_dir.display());

    let Some(aiken) = which_aiken() else {
        eprintln!("`aiken` not found on PATH — skipping `aiken check`");
        return;
    };

    let output = Command::new(&aiken)
        .arg("check")
        .current_dir(&out_dir)
        .output()
        .expect("failed to run aiken check");

    if !output.status.success() {
        panic!(
            "aiken check failed\n--- stdout ---\n{}\n--- stderr ---\n{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr),
        );
    }
}

fn which_aiken() -> Option<String> {
    let probe = if cfg!(windows) { "where" } else { "which" };
    let out = Command::new(probe).arg("aiken").output().ok()?;
    if !out.status.success() {
        return None;
    }
    let path = String::from_utf8_lossy(&out.stdout)
        .lines()
        .next()?
        .trim()
        .to_string();
    (!path.is_empty()).then_some(path)
}
