//! The Composer — stitches one Layer 1 ([`OuterBackend`]) and one Layer 2
//! ([`Layer2Codegen`]) into a ready-to-`aiken check` project.
//!
//! It owns **all** Aiken string assembly. It renders Layer 1 (outer VK baked)
//! into `lib/zkwrap/<backend>.ak`, vendors the generic Layer 2 verbatim into
//! `lib/zkwrap/<system>.ak`, and generates `validators/verify.ak`: the
//! app/inner-binding const block, the composed entry point, and the supplied
//! fixture tests. It carries no per-backend or per-system knowledge — only the
//! two traits and the universal seam.

use std::path::PathBuf;

use serde_json::Value;

use crate::codegen::{CodegenError, Layer2Codegen, OuterBackend};
use crate::OuterVk;

/// A single generated `test` block, supplied by the caller as data so the
/// Composer needs no per-backend/per-system test knowledge. Rendered into
/// `validators/verify.ak`, where it can reference the baked consts, the
/// composed `verify`, and the imported Layer 1 / Layer 2 modules.
#[derive(Debug, Clone)]
pub struct TestBlock {
    pub name:        String,
    /// An Aiken expression that evaluates to `Bool`.
    pub body:        String,
    /// Emit `test name() fail { … }` (a tamper-negative test).
    pub should_fail: bool,
}

impl TestBlock {
    pub fn pass(name: impl Into<String>, body: impl Into<String>) -> Self {
        TestBlock { name: name.into(), body: body.into(), should_fail: false }
    }
    pub fn fail(name: impl Into<String>, body: impl Into<String>) -> Self {
        TestBlock { name: name.into(), body: body.into(), should_fail: true }
    }
}

/// Everything the Composer needs to assemble one project.
pub struct ComposeRequest<'a> {
    /// Aiken project name, `namespace/name` form (e.g. `"zkwrap/risc0_groth16"`).
    pub project_name:  &'a str,
    pub backend:       &'a dyn OuterBackend,
    pub layer2:        &'a dyn Layer2Codegen,
    pub vk:            &'a OuterVk,
    /// `inner_vk_hash` from `outer_proof.json` — raw lowercase hex, no `0x`.
    pub inner_vk_hash: &'a str,
    /// The canonical inner proof's `meta.json` `codegen` section.
    pub codegen_meta:  &'a Value,
    /// Fixture tests to emit (see [`TestBlock`]). May be empty.
    pub tests:         &'a [TestBlock],
}

/// The in-memory result: relative path → file content. [`Self::write_to`]
/// materializes it on disk.
pub struct GeneratedProject {
    pub files: Vec<(PathBuf, String)>,
}

impl GeneratedProject {
    pub fn write_to(&self, root: &std::path::Path) -> std::io::Result<()> {
        for (rel, content) in &self.files {
            let path = root.join(rel);
            if let Some(parent) = path.parent() {
                std::fs::create_dir_all(parent)?;
            }
            std::fs::write(path, content)?;
        }
        Ok(())
    }

    /// Look up a generated file by its forward-slash relative path (tests).
    pub fn get(&self, rel: &str) -> Option<&str> {
        let want = PathBuf::from(rel);
        self.files
            .iter()
            .find(|(p, _)| *p == want)
            .map(|(_, c)| c.as_str())
    }
}

/// Assemble the project.
pub fn compose(req: &ComposeRequest) -> Result<GeneratedProject, CodegenError> {
    // --- consistency checks the Composer can make from the two traits + VK ---
    if req.vk.backend != req.backend.backend_id() {
        return Err(CodegenError::Render(format!(
            "outer_vk backend {:?} != backend {:?}",
            req.vk.backend,
            req.backend.backend_id()
        )));
    }
    let n_real = req.layer2.n_real();
    let max_inputs = req.vk.max_inputs;
    if n_real > max_inputs {
        return Err(CodegenError::Meta(format!(
            "n_real {n_real} exceeds MAX_INPUTS {max_inputs}"
        )));
    }

    let layer1_src = req.backend.render_layer1(req.vk)?;
    let layer2_src = req.layer2.layer2_source();
    let wiring = req.layer2.layer2_wiring(req.codegen_meta)?;

    let validator_src = render_validator(req, &wiring, n_real, max_inputs);

    let backend_mod = req.backend.module_name();
    let system_mod = req.layer2.module_name();

    let files = vec![
        (PathBuf::from("aiken.toml"), aiken_toml(req.project_name)),
        (PathBuf::from(format!("lib/zkwrap/{backend_mod}.ak")), layer1_src),
        (PathBuf::from(format!("lib/zkwrap/{system_mod}.ak")), layer2_src.to_string()),
        (PathBuf::from("validators/verify.ak"), validator_src),
    ];

    Ok(GeneratedProject { files })
}

fn aiken_toml(project_name: &str) -> String {
    format!(
        r#"# GENERATED by zkwrap-core's Composer (ADR-0007). Do not edit by hand.
name = "{project_name}"
version = "0.0.0"
plutus = "v3"
compiler = "1.1.19"
description = "Generated zkwrap outer-wrapper verifier."

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"
"#
    )
}

/// Generate `validators/verify.ak`: imports, the app/inner-binding const block,
/// the composed entry point (Layer 2 → pad → Layer 1), and the fixture tests.
fn render_validator(
    req: &ComposeRequest,
    wiring: &crate::codegen::Layer2Wiring,
    n_real: usize,
    max_inputs: usize,
) -> String {
    let backend_mod = req.backend.module_name();
    let system_mod = req.layer2.module_name();

    let mut out = String::new();
    out.push_str(
        "// GENERATED by zkwrap-core's Composer. Do not edit by hand.\n//\n\
         // Holds the policy surface: the app/inner-binding constants and the wiring of\n\
         // Layer 2 (inner-system scaffolding) into Layer 1 (proving engine). Promoting a\n\
         // constant to a redeemer field is a one-line edit at the call site below.\n\n",
    );
    out.push_str(&format!("use zkwrap/{backend_mod}\n"));
    out.push_str(&format!("use zkwrap/{system_mod}\n\n"));

    // ---- app/inner-binding constants ----
    out.push_str("// =====================================================================\n");
    out.push_str("// App/inner-binding constants (baked at codegen; may move to redeemer).\n");
    out.push_str("// =====================================================================\n");
    out.push_str(&format!(
        "const inner_vk_hash: Int = 0x{}\n\n",
        req.inner_vk_hash
    ));
    for c in &wiring.consts {
        out.push_str(c);
        out.push('\n');
    }
    out.push('\n');

    // ---- composed entry point ----
    let proof_params = req.backend.proof_params();
    let mut params: Vec<String> = proof_params
        .iter()
        .map(|p| format!("{p}: ByteArray"))
        .collect();
    for rp in &wiring.raw_params {
        params.push(format!("{}: {}", rp.name, rp.ty));
    }

    // Destructure idents i0..i{n_real-1} and the MAX_INPUTS-padded inputs list.
    let idents: Vec<String> = (0..n_real).map(|i| format!("i{i}")).collect();
    let mut padded: Vec<String> = idents.clone();
    padded.extend(std::iter::repeat("0".to_string()).take(max_inputs - n_real));

    let forwarded_proof = proof_params.join(", ");

    out.push_str("// =====================================================================\n");
    out.push_str(
        "// Composed entry: Layer 2 derives the n_real real inputs; we length-pin them,\n\
         // pad to MAX_INPUTS with literal zeros (ADR-0002 excess-zero enforcement), and\n\
         // hand the full public-input vector to Layer 1.\n",
    );
    out.push_str("// =====================================================================\n");
    out.push_str(&format!("pub fn verify(\n  {},\n) -> Bool {{\n", params.join(",\n  ")));
    out.push_str(&format!("  let reals = {}\n", wiring.call_expr));
    out.push_str(&format!("  expect [{}] = reals\n", idents.join(", ")));
    out.push_str(&format!(
        "  {backend_mod}.verify(\n    {forwarded_proof},\n    inner_vk_hash,\n    [{}],\n  )\n}}\n",
        padded.join(", ")
    ));

    // ---- fixture tests ----
    if !req.tests.is_empty() {
        out.push('\n');
        out.push_str("// =====================================================================\n");
        out.push_str("// Fixture tests (lifted from the spike against the pinned proof).\n");
        out.push_str("// =====================================================================\n");
        for t in req.tests {
            let fail = if t.should_fail { " fail" } else { "" };
            out.push_str(&format!("\ntest {}(){} {{\n{}\n}}\n", t.name, fail, indent(&t.body)));
        }
    }

    out
}

/// Indent each line of a multi-line test body by two spaces.
fn indent(body: &str) -> String {
    body.lines()
        .map(|l| if l.is_empty() { String::new() } else { format!("  {l}") })
        .collect::<Vec<_>>()
        .join("\n")
}
