//! Acceptance test: the RISC Zero validator factory ([`build_validator`]) must
//! emit a full Aiken project that `aiken check`s green against the pinned
//! fixtures — driven exactly as a host would drive it (canonicalize the
//! committed receipt, feed the committed outer proof), with the standard test
//! suite generated by the factory rather than hand-written here.
//!
//! The project is written under the workspace `target/` (gitignored) so it can
//! be inspected after the run. If `aiken` is not on `PATH` the test still
//! validates generation and the `aiken check` step is skipped with a notice.

use std::path::{Path, PathBuf};
use std::process::Command;

use risc0_zkvm::sha::Digest;
use risc0_zkvm::Receipt;

use zkwrap_core::OuterProof;
use zkwrap_risc0::{build_validator, canonicalize, Risc0ValidatorRequest};

fn repo_path(rel: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join(rel)
}

fn read(rel: &str) -> String {
    std::fs::read_to_string(repo_path(rel)).unwrap()
}

fn read_bytes(rel: &str) -> Vec<u8> {
    std::fs::read(repo_path(rel)).unwrap()
}

#[test]
fn factory_emits_aiken_check_passing_project() {
    // Drive it like a host: verify + canonicalize the committed receipt, then
    // pair it with the committed outer proof.
    let receipt: Receipt =
        serde_json::from_str(&read("fixtures/risc0-hello-world/receipt.json")).unwrap();
    let image_id =
        Digest::try_from(read_bytes("fixtures/risc0-hello-world/image_id.bin").as_slice()).unwrap();
    let canonical = canonicalize(&receipt, image_id).unwrap();

    let vk_json = read("fixtures/groth16-setup/outer_vk.json");
    let outer = OuterProof::from_json(&read(
        "fixtures/outer-proofs/risc0-groth16-outer-proof.json",
    ))
    .unwrap();

    let project = build_validator(&Risc0ValidatorRequest {
        receipt: &receipt,
        canonical: &canonical,
        outer_proof: &outer,
        outer_vk_json: &vk_json,
        project_name: "zkwrap/risc0_groth16",
    })
    .unwrap();

    // Generation sanity: required files present, no unrendered template holes.
    let validator = project
        .get("validators/verify.ak")
        .expect("validators/verify.ak");
    let layer1 = project
        .get("lib/zkwrap/groth16.ak")
        .expect("lib/zkwrap/groth16.ak");
    let layer2 = project
        .get("lib/zkwrap/risc0.ak")
        .expect("lib/zkwrap/risc0.ak");
    for (name, src) in [
        ("groth16", layer1),
        ("risc0", layer2),
        ("verify", validator),
    ] {
        assert!(
            !src.contains("{{") && !src.contains("{%"),
            "{name}.ak has unrendered holes"
        );
    }
    assert!(validator.contains("const inner_vk_hash: Int = 0x0c42ca6b"));

    // Materialize under the (gitignored) target dir for inspection + aiken check.
    let out_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../target/generated/risc0-verifier");
    let _ = std::fs::remove_dir_all(&out_dir);
    project.write_to(&out_dir).unwrap();
    eprintln!("generated project at {}", out_dir.display());

    let Some(aiken) = which_aiken() else {
        eprintln!("`aiken` not found on PATH — skipping `aiken check`");
        return;
    };

    let output = Command::new(&aiken)
        .arg("check")
        .current_dir(&out_dir)
        .output()
        .expect("failed to run aiken check");

    if !output.status.success() {
        panic!(
            "aiken check failed\n--- stdout ---\n{}\n--- stderr ---\n{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr),
        );
    }
}

fn which_aiken() -> Option<String> {
    let probe = if cfg!(windows) { "where" } else { "which" };
    let out = Command::new(probe).arg("aiken").output().ok()?;
    if !out.status.success() {
        return None;
    }
    let path = String::from_utf8_lossy(&out.stdout)
        .lines()
        .next()?
        .trim()
        .to_string();
    (!path.is_empty()).then_some(path)
}
