//! Acceptance test: the RISC Zero validator factory ([`build_validator`]) must
//! emit a full Aiken project that `aiken check`s green against the pinned
//! fixtures — driven exactly as a host would drive it (canonicalize the
//! committed receipt, feed the committed outer proof), with the standard test
//! suite generated by the factory rather than hand-written here.
//!
//! Runs once per outer backend (Groth16 and PLONK) against that backend's
//! committed `outer_vk.json` + outer proof; the inner (RISC Zero) layer and the
//! receipt are shared. The project is written under the workspace `target/`
//! (gitignored) so it can be inspected after the run. If `aiken` is not on
//! `PATH` the test still validates generation and the `aiken check` step is
//! skipped with a notice.

use std::path::{Path, PathBuf};
use std::process::Command;

use risc0_zkvm::sha::Digest;
use risc0_zkvm::Receipt;

use zkwrap_core::{Groth16OuterProof, OuterProof, PlonkOuterProof};
use zkwrap_risc0::{build_validator, canonicalize, Risc0ValidatorRequest};

fn repo_path(rel: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join(rel)
}

fn read(rel: &str) -> String {
    std::fs::read_to_string(repo_path(rel)).unwrap()
}

fn read_bytes(rel: &str) -> Vec<u8> {
    std::fs::read(repo_path(rel)).unwrap()
}

#[test]
fn factory_emits_aiken_check_passing_project_groth16() {
    run_case::<Groth16OuterProof>(
        "groth16",
        "fixtures/groth16-setup/outer_vk.json",
        "fixtures/outer-proofs/risc0-groth16-outer-proof.json",
        "risc0-verifier",
    );
}

#[test]
fn factory_emits_aiken_check_passing_project_plonk() {
    run_case::<PlonkOuterProof>(
        "plonk",
        "fixtures/plonk-setup/outer_vk.json",
        "fixtures/outer-proofs/risc0-plonk-outer-proof.json",
        "risc0-verifier-plonk",
    );
}

/// Build + `aiken check` the RISC Zero validator for one outer backend `P`.
fn run_case<P: OuterProof>(outer_mod: &str, vk_rel: &str, proof_rel: &str, out_subdir: &str) {
    // Drive it like a host: verify + canonicalize the committed receipt, then
    // pair it with the committed outer proof.
    let receipt: Receipt =
        serde_json::from_str(&read("fixtures/risc0-hello-world/receipt.json")).unwrap();
    let image_id =
        Digest::try_from(read_bytes("fixtures/risc0-hello-world/image_id.bin").as_slice()).unwrap();
    let canonical = canonicalize(&receipt, image_id).unwrap();

    let vk_json = read(vk_rel);
    let outer = P::from_json(&read(proof_rel)).unwrap();

    let project = build_validator(&Risc0ValidatorRequest {
        receipt: &receipt,
        canonical: &canonical,
        outer_proof: &outer,
        outer_vk_json: &vk_json,
        project_name: "zkwrap/risc0_verifier",
    })
    .unwrap();

    // Generation sanity: required files present, no unrendered template holes.
    let validator = project
        .get("validators/verify.ak")
        .expect("validators/verify.ak");
    let layer1 = project
        .get(&format!("lib/zkwrap/{outer_mod}.ak"))
        .expect("outer layer module");
    let layer2 = project
        .get("lib/zkwrap/risc0.ak")
        .expect("lib/zkwrap/risc0.ak");
    for (name, src) in [
        (outer_mod, layer1),
        ("risc0", layer2),
        ("verify", validator),
    ] {
        assert!(
            !src.contains("{{") && !src.contains("{%"),
            "{name}.ak has unrendered holes"
        );
    }
    // The baked inner_vk_hash matches the proof (it differs per backend because
    // the InnerVKHash preimage depends on the wrapper's input count).
    let vkhash_prefix = &outer.inner_vk_hash()[..8];
    assert!(
        validator.contains(&format!("const inner_vk_hash: Int = 0x{vkhash_prefix}")),
        "inner_vk_hash const should start with 0x{vkhash_prefix}"
    );

    // Materialize under the (gitignored) target dir for inspection + aiken check.
    let out_dir = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../target/generated")
        .join(out_subdir);
    let _ = std::fs::remove_dir_all(&out_dir);
    project.write_to(&out_dir).unwrap();
    eprintln!("generated {outer_mod} project at {}", out_dir.display());

    let Some(aiken) = which_aiken() else {
        eprintln!("`aiken` not found on PATH — skipping `aiken check`");
        return;
    };

    let output = Command::new(&aiken)
        .arg("check")
        .current_dir(&out_dir)
        .output()
        .expect("failed to run aiken check");

    if !output.status.success() {
        panic!(
            "aiken check failed ({outer_mod})\n--- stdout ---\n{}\n--- stderr ---\n{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr),
        );
    }
}

fn which_aiken() -> Option<String> {
    let probe = if cfg!(windows) { "where" } else { "which" };
    let out = Command::new(probe).arg("aiken").output().ok()?;
    if !out.status.success() {
        return None;
    }
    let path = String::from_utf8_lossy(&out.stdout)
        .lines()
        .next()?
        .trim()
        .to_string();
    (!path.is_empty()).then_some(path)
}
